"""empty message

Revision ID: cc94ad5ceecc
Revises: 4254ed61099b
Create Date: 2022-08-14 11:59:38.697653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc94ad5ceecc'
down_revision = '4254ed61099b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_enue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_enue')
    # ### end Alembic commands ###
