"""empty message

Revision ID: e9e1340283b7
Revises: 07a60f78a8cd
Create Date: 2022-08-11 23:54:40.887686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e1340283b7'
down_revision = '07a60f78a8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'website_link')
    op.alter_column('show', 'start_time',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website')
    op.alter_column('show', 'start_time',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
